### ISSUE TITLE
Support for 12.2.1.2.0 needed

### ISSUE THREAD

**Issue by rstyczynski** [coherence-community/coherence-spring#17]
Hi,

is it safe change version to 12.2.1.2.0 in? 

        <oracle.coherence.version>12.1.2-0-4</oracle.coherence.version>

Should it be done on your side?

Thanks.
Ryszard

**Comment by rstyczynski** [comment]
**does not work.** 

mvn clean install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Coherence Spring Integration Project
[INFO] Coherence Spring Integration
[INFO] Coherence Spring Integration Tests
[INFO] Coherence Spring Site
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Coherence Spring Integration Project 1.1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ coherence-spring-integration ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-plugin-versions) @ coherence-spring-integration ---
[INFO] 
[INFO] >>> maven-source-plugin:2.2.1:jar (attach-sources) > generate-sources @ coherence-spring-integration >>>
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-plugin-versions) @ coherence-spring-integration ---
[INFO] 
[INFO] <<< maven-source-plugin:2.2.1:jar (attach-sources) < generate-sources @ coherence-spring-integration <<<
[INFO] 
[INFO] --- maven-source-plugin:2.2.1:jar (attach-sources) @ coherence-spring-integration ---
[INFO] 
[INFO] --- maven-javadoc-plugin:2.9.1:jar (attach-javadocs) @ coherence-spring-integration ---
[INFO] Not executing Javadoc as the project is not a Java classpath-capable package
[INFO] 
[INFO] --- maven-gpg-plugin:1.5:sign (sign-artifacts) @ coherence-spring-integration ---
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ coherence-spring-integration ---
[INFO] Installing /home/dev/coherence-spring-master/pom.xml to /Users/rstyczynski/.m2/repository/com/oracle/coherence/spring/coherence-spring-integration/1.1.0-SNAPSHOT/coherence-spring-integration-1.1.0-SNAPSHOT.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Coherence Spring Integration 1.1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ coherence-spring ---
[INFO] Deleting /home/dev/coherence-spring-master/coherence-spring/target
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-plugin-versions) @ coherence-spring ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ coherence-spring ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ coherence-spring ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to /home/dev/coherence-spring-master/coherence-spring/target/classes
[WARNING] /home/dev/coherence-spring-master/coherence-spring/src/main/java/com/oracle/coherence/spring/SpringNamespaceHandler.java: /home/dev/coherence-spring-master/coherence-spring/src/main/java/com/oracle/coherence/spring/SpringNamespaceHandler.java uses or overrides a deprecated API.
[WARNING] /home/dev/coherence-spring-master/coherence-spring/src/main/java/com/oracle/coherence/spring/SpringNamespaceHandler.java: Recompile with -Xlint:deprecation for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ coherence-spring ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/dev/coherence-spring-master/coherence-spring/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ coherence-spring ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ coherence-spring ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ coherence-spring ---
[INFO] Building jar: /home/dev/coherence-spring-master/coherence-spring/target/coherence-spring-1.1.0-SNAPSHOT.jar
[INFO] 
[INFO] >>> maven-source-plugin:2.2.1:jar (attach-sources) > generate-sources @ coherence-spring >>>
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-plugin-versions) @ coherence-spring ---
[INFO] 
[INFO] <<< maven-source-plugin:2.2.1:jar (attach-sources) < generate-sources @ coherence-spring <<<
[INFO] 
[INFO] --- maven-source-plugin:2.2.1:jar (attach-sources) @ coherence-spring ---
[INFO] Building jar: /home/dev/coherence-spring-master/coherence-spring/target/coherence-spring-1.1.0-SNAPSHOT-sources.jar
[INFO] 
[INFO] --- maven-javadoc-plugin:2.9.1:jar (attach-javadocs) @ coherence-spring ---
[INFO] 
Loading source files for package com.oracle.coherence.spring...
Constructing Javadoc information...
Standard Doclet version 1.8.0_60
Building tree for all the packages and classes...
Generating /home/dev/coherence-spring-master/coherence-spring/target/apidocs/com/oracle/coherence/spring/CoherenceBeanExpressionResolver.html...
Generating /home/dev/coherence-spring-master/coherence-spring/target/apidocs/com/oracle/coherence/spring/SpringBasedCoherenceSession.html...
Generating /home/dev/coherence-spring-master/coherence-spring/target/apidocs/com/oracle/coherence/spring/SpringNamespaceHandler.html...
Generating /home/dev/coherence-spring-master/coherence-spring/target/apidocs/com/oracle/coherence/spring/SpringNamespaceHandler.PropertyProcessor.html...
Generating /home/dev/coherence-spring-master/coherence-spring/target/apidocs/com/oracle/coherence/spring/SpringNamespaceHandler.SpringBeanBuilder.html...
Generating /home/dev/coherence-spring-master/coherence-spring/target/apidocs/com/oracle/coherence/spring/SpringNamespaceHandler.SpringBeanFactoryBuilder.html...
Generating /home/dev/coherence-spring-master/coherence-spring/target/apidocs/com/oracle/coherence/spring/SpringNamespaceHandler.SpringBeanFactoryBuilder.CoherenceApplicationContext.html...
Generating /home/dev/coherence-spring-master/coherence-spring/target/apidocs/com/oracle/coherence/spring/package-frame.html...
Generating /home/dev/coherence-spring-master/coherence-spring/target/apidocs/com/oracle/coherence/spring/package-summary.html...
Generating /home/dev/coherence-spring-master/coherence-spring/target/apidocs/com/oracle/coherence/spring/package-tree.html...
Generating /home/dev/coherence-spring-master/coherence-spring/target/apidocs/constant-values.html...
Generating /home/dev/coherence-spring-master/coherence-spring/target/apidocs/com/oracle/coherence/spring/class-use/SpringNamespaceHandler.html...
Generating /home/dev/coherence-spring-master/coherence-spring/target/apidocs/com/oracle/coherence/spring/class-use/SpringNamespaceHandler.PropertyProcessor.html...
Generating /home/dev/coherence-spring-master/coherence-spring/target/apidocs/com/oracle/coherence/spring/class-use/SpringNamespaceHandler.SpringBeanBuilder.html...
Generating /home/dev/coherence-spring-master/coherence-spring/target/apidocs/com/oracle/coherence/spring/class-use/SpringNamespaceHandler.SpringBeanFactoryBuilder.html...
Generating /home/dev/coherence-spring-master/coherence-spring/target/apidocs/com/oracle/coherence/spring/class-use/SpringNamespaceHandler.SpringBeanFactoryBuilder.CoherenceApplicationContext.html...
Generating /home/dev/coherence-spring-master/coherence-spring/target/apidocs/com/oracle/coherence/spring/class-use/SpringBasedCoherenceSession.html...
Generating /home/dev/coherence-spring-master/coherence-spring/target/apidocs/com/oracle/coherence/spring/class-use/CoherenceBeanExpressionResolver.html...
Generating /home/dev/coherence-spring-master/coherence-spring/target/apidocs/com/oracle/coherence/spring/package-use.html...
Building index for all the packages and classes...
Generating /home/dev/coherence-spring-master/coherence-spring/target/apidocs/overview-tree.html...
Generating /home/dev/coherence-spring-master/coherence-spring/target/apidocs/index-all.html...
Generating /home/dev/coherence-spring-master/coherence-spring/target/apidocs/deprecated-list.html...
Building index for all classes...
Generating /home/dev/coherence-spring-master/coherence-spring/target/apidocs/allclasses-frame.html...
Generating /home/dev/coherence-spring-master/coherence-spring/target/apidocs/allclasses-noframe.html...
Generating /home/dev/coherence-spring-master/coherence-spring/target/apidocs/index.html...
Generating /home/dev/coherence-spring-master/coherence-spring/target/apidocs/help-doc.html...
5 errors
1 warning
[ERROR] MavenReportException: Error while creating archive: 
Exit code: 1 - /home/dev/coherence-spring-master/coherence-spring/src/main/java/com/oracle/coherence/spring/CoherenceBeanExpressionResolver.java:92: warning: no @param for exprParser
    public CoherenceBeanExpressionResolver(com.tangosol.config.expression.ExpressionParser exprParser)
           ^
/home/dev/coherence-spring-master/coherence-spring/src/main/java/com/oracle/coherence/spring/SpringBasedCoherenceSession.java:69: error: unknown tag: Configuration
 * @Configuration
   ^
/home/dev/coherence-spring-master/coherence-spring/src/main/java/com/oracle/coherence/spring/SpringBasedCoherenceSession.java:72: error: unknown tag: Bean
 *     @Bean
       ^
/home/dev/coherence-spring-master/coherence-spring/src/main/java/com/oracle/coherence/spring/SpringBasedCoherenceSession.java:84: error: unknown tag: Configuration
 * @Configuration
   ^
/home/dev/coherence-spring-master/coherence-spring/src/main/java/com/oracle/coherence/spring/SpringBasedCoherenceSession.java:87: error: unknown tag: Bean
 *     @Bean
       ^
/home/dev/coherence-spring-master/coherence-spring/src/main/java/com/oracle/coherence/spring/SpringBasedCoherenceSession.java:93: error: unknown tag: Bean
 *     @Bean
       ^

Command line was: /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin/javadoc @options @packages

Refer to the generated Javadoc files in '/home/dev/coherence-spring-master/coherence-spring/target/apidocs' dir.

org.apache.maven.reporting.MavenReportException: 
Exit code: 1 - /home/dev/coherence-spring-master/coherence-spring/src/main/java/com/oracle/coherence/spring/CoherenceBeanExpressionResolver.java:92: warning: no @param for exprParser
    public CoherenceBeanExpressionResolver(com.tangosol.config.expression.ExpressionParser exprParser)
           ^
/home/dev/coherence-spring-master/coherence-spring/src/main/java/com/oracle/coherence/spring/SpringBasedCoherenceSession.java:69: error: unknown tag: Configuration
 * @Configuration
   ^
/home/dev/coherence-spring-master/coherence-spring/src/main/java/com/oracle/coherence/spring/SpringBasedCoherenceSession.java:72: error: unknown tag: Bean
 *     @Bean
       ^
/home/dev/coherence-spring-master/coherence-spring/src/main/java/com/oracle/coherence/spring/SpringBasedCoherenceSession.java:84: error: unknown tag: Configuration
 * @Configuration
   ^
/home/dev/coherence-spring-master/coherence-spring/src/main/java/com/oracle/coherence/spring/SpringBasedCoherenceSession.java:87: error: unknown tag: Bean
 *     @Bean
       ^
/home/dev/coherence-spring-master/coherence-spring/src/main/java/com/oracle/coherence/spring/SpringBasedCoherenceSession.java:93: error: unknown tag: Bean
 *     @Bean
       ^

Command line was: /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin/javadoc @options @packages

Refer to the generated Javadoc files in '/home/dev/coherence-spring-master/coherence-spring/target/apidocs' dir.

	at org.apache.maven.plugin.javadoc.AbstractJavadocMojo.executeJavadocCommandLine(AbstractJavadocMojo.java:5074)
	at org.apache.maven.plugin.javadoc.AbstractJavadocMojo.executeReport(AbstractJavadocMojo.java:1999)
	at org.apache.maven.plugin.javadoc.JavadocJar.execute(JavadocJar.java:181)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] 
[INFO] --- maven-gpg-plugin:1.5:sign (sign-artifacts) @ coherence-spring ---
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ coherence-spring ---
[INFO] Installing /home/dev/coherence-spring-master/coherence-spring/target/coherence-spring-1.1.0-SNAPSHOT.jar to /Users/rstyczynski/.m2/repository/com/oracle/coherence/spring/coherence-spring/1.1.0-SNAPSHOT/coherence-spring-1.1.0-SNAPSHOT.jar
[INFO] Installing /home/dev/coherence-spring-master/coherence-spring/pom.xml to /Users/rstyczynski/.m2/repository/com/oracle/coherence/spring/coherence-spring/1.1.0-SNAPSHOT/coherence-spring-1.1.0-SNAPSHOT.pom
[INFO] Installing /home/dev/coherence-spring-master/coherence-spring/target/coherence-spring-1.1.0-SNAPSHOT-sources.jar to /Users/rstyczynski/.m2/repository/com/oracle/coherence/spring/coherence-spring/1.1.0-SNAPSHOT/coherence-spring-1.1.0-SNAPSHOT-sources.jar
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Coherence Spring Integration Tests 1.1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ coherence-spring-tests ---
[INFO] Deleting /home/dev/coherence-spring-master/coherence-spring-tests/target
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-plugin-versions) @ coherence-spring-tests ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ coherence-spring-tests ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/dev/coherence-spring-master/coherence-spring-tests/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ coherence-spring-tests ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ coherence-spring-tests ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ coherence-spring-tests ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 6 source files to /home/dev/coherence-spring-master/coherence-spring-tests/target/test-classes
[INFO] -------------------------------------------------------------
[WARNING] COMPILATION WARNING : 
[INFO] -------------------------------------------------------------
[WARNING] /home/dev/coherence-spring-master/coherence-spring-tests/src/test/java/com/oracle/coherence/spring/SpringApplicationTests.java: Some input files use or override a deprecated API.
[WARNING] /home/dev/coherence-spring-master/coherence-spring-tests/src/test/java/com/oracle/coherence/spring/SpringApplicationTests.java: Recompile with -Xlint:deprecation for details.
[WARNING] /home/dev/coherence-spring-master/coherence-spring-tests/src/test/java/com/oracle/coherence/spring/StubNamedCacheStore.java: Some input files use unchecked or unsafe operations.
[WARNING] /home/dev/coherence-spring-master/coherence-spring-tests/src/test/java/com/oracle/coherence/spring/StubNamedCacheStore.java: Recompile with -Xlint:unchecked for details.
[INFO] 4 warnings 
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/dev/coherence-spring-master/coherence-spring-tests/src/test/java/com/oracle/coherence/spring/StubInterceptor.java:[37,58] type argument com.tangosol.net.events.partition.cache.EntryEvent is not within bounds of type-variable E
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Coherence Spring Integration Project ............... SUCCESS [  0.851 s]
[INFO] Coherence Spring Integration ....................... SUCCESS [  2.380 s]
[INFO] Coherence Spring Integration Tests ................. FAILURE [  0.150 s]
[INFO] Coherence Spring Site .............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.503 s
[INFO] Finished at: 2017-07-13T13:51:35+02:00
[INFO] Final Memory: 27M/312M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project coherence-spring-tests: Compilation failure
[ERROR] /home/dev/coherence-spring-master/coherence-spring-tests/src/test/java/com/oracle/coherence/spring/StubInterceptor.java:[37,58] type argument com.tangosol.net.events.partition.cache.EntryEvent is not within bounds of type-variable E
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :coherence-spring-tests

**Comment by brianoliver** [comment]
This compilation error is due to Java generics incompatibility.  This is resolved as part of #8
